/* scemu GUI: the front-panel button combinations the SC-88Pro understands.
 *
 * Copyright (c) 2026 ian karlsson
 * SPDX-License-Identifier: BSD-3-Clause
 */
#include <stdio.h>
#include "combos.h"

#define B(x) SCEMU_BUTTON_##x
#define NONE SCEMU_BUTTON_COUNT

const combo_t combos[] = {
	/* Chapter 1 -- Try out the unit */
	{ "the value will change faster",
	  "Holding one half of the Part pair and pressing the other steps the Part number quickly.",
	  NULL,
	  { B(PART_LEFT) }, 1, B(PART_RIGHT), false, 6, COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Instrument pair and pressing the other steps the sound quickly.",
	  NULL,
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, 6, COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Level pair and pressing the other changes the level quickly.",
	  NULL,
	  { B(LEVEL_LEFT) }, 1, B(LEVEL_RIGHT), false, 6, COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Pan pair and pressing the other changes the pan quickly.",
	  NULL,
	  { B(PAN_LEFT) }, 1, B(PAN_RIGHT), false, 6, COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Reverb pair and pressing the other changes the reverb level quickly.",
	  NULL,
	  { B(REVERB_LEFT) }, 1, B(REVERB_RIGHT), false, 6, COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Chorus pair and pressing the other changes the chorus level quickly.",
	  NULL,
	  { B(CHORUS_LEFT) }, 1, B(CHORUS_RIGHT), false, 6, COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Key Shift pair and pressing the other transposes quickly.",
	  NULL,
	  { B(KEY_SHIFT_LEFT) }, 1, B(KEY_SHIFT_RIGHT), false, 6, COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the MIDI Channel pair and pressing the other steps the channel quickly.",
	  NULL,
	  { B(MIDI_CH_LEFT) }, 1, B(MIDI_CH_RIGHT), false, 6, COMBO_HOLD_THEN_PRESS },
	{ "Adjust the amount of delay",
	  "Lowers the delay send level of the Part, or of all Parts when the ALL indicator is lit.",
	  "Part or All display",
	  { B(SC88_MAP) }, 1, B(KEY_SHIFT_LEFT), false, 13, COMBO_HOLD_THEN_PRESS },
	{ "Adjust the amount of delay",
	  "Raises the delay send level of the Part, or of all Parts when the ALL indicator is lit.",
	  "Part or All display",
	  { B(SC88_MAP) }, 1, B(KEY_SHIFT_RIGHT), false, 13, COMBO_HOLD_THEN_PRESS },

	/* Chapter 2 -- Parts and parameters */
	{ "To switch between the group A and B",
	  "Flips the Part display between Parts A01-A16 and Parts B01-B16.",
	  "Part display",
	  { B(ALL) }, 1, B(PART_LEFT), false, 18, COMBO_TOGETHER },
	{ "Variation select mode",
	  "Enters and leaves Variation select, where the Instrument buttons pick the Variation number.",
	  "Part display",
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, 20, COMBO_TOGETHER },
	{ "To switch between the A and B",
	  "Flips the Part's MIDI channel display between group A and group B channels.",
	  "Part display",
	  { B(KEY_SHIFT_RIGHT) }, 1, B(MIDI_CH_LEFT), false, 22, COMBO_TOGETHER },
	{ "Part Monitor",
	  "Listens to the selected Part alone; the Mute indicator blinks while the monitor is on.",
	  "Part display",
	  { B(ALL) }, 1, B(MUTE), false, 25, COMBO_TOGETHER },
	{ "the current setting will be shown graphically",
	  "Draws the Level of every Part as bars; the same press returns to the normal display.",
	  "Part or All display",
	  { B(LEVEL_LEFT) }, 1, B(LEVEL_RIGHT), false, 25, COMBO_TOGETHER },
	{ "the current setting will be shown graphically",
	  "Draws Pan graphically; the same press returns to the normal display.",
	  "Part or All display",
	  { B(PAN_LEFT) }, 1, B(PAN_RIGHT), false, 25, COMBO_TOGETHER },
	{ "the current setting will be shown graphically",
	  "Draws Key Shift graphically; the same press returns to the normal display.",
	  "Part or All display",
	  { B(KEY_SHIFT_LEFT) }, 1, B(KEY_SHIFT_RIGHT), false, 25, COMBO_TOGETHER },
	{ "Parameters that must be selected from the menu",
	  "Opens and closes the per-Part parameter menu, from Part EQ to the CC1 LFO block.",
	  "Part display",
	  { B(PART_LEFT) }, 1, B(PART_RIGHT), false, 26, COMBO_TOGETHER },
	{ "Parameter jump",
	  "Skips the menu cursor up to the head of the next parameter block.",
	  "any menu",
	  { B(SELECT) }, 1, B(SC55_MAP), false, 26, COMBO_HOLD_THEN_PRESS },
	{ "Parameter jump",
	  "Skips the menu cursor down to the head of the next parameter block.",
	  "any menu",
	  { B(SELECT) }, 1, B(SC88_MAP), false, 26, COMBO_HOLD_THEN_PRESS },
	{ "setting status ... graphically",
	  "Draws Vibrato Rate, Attack Time or the EFX type row graphically; the same press returns.",
	  "Part display",
	  { B(EDIT1_LEFT) }, 1, B(EDIT1_RIGHT), false, 31, COMBO_TOGETHER },
	{ "setting status ... graphically",
	  "Draws Vibrato Depth, Cutoff or Decay graphically; the same press returns.",
	  "Part display",
	  { B(EDIT2_LEFT) }, 1, B(EDIT2_RIGHT), false, 31, COMBO_TOGETHER },
	{ "setting status ... graphically",
	  "Draws Vibrato Delay, Resonance or Release graphically; the same press returns.",
	  "Part display",
	  { B(EDIT3_LEFT) }, 1, B(EDIT3_RIGHT), false, 31, COMBO_TOGETHER },
	{ "Setting parameters common to all Parts",
	  "Opens and closes the all-Parts menu: M. Tune, the system effects, EFX control, Device ID and the receive switches.",
	  "All display (ALL lit)",
	  { B(PART_LEFT) }, 1, B(PART_RIGHT), false, 14, COMBO_TOGETHER },
	{ "System parameter settings",
	  "Opens and closes the System-parameter menu, from Preview Note to Patch Load Initialize.",
	  NULL,
	  { B(SC55_MAP) }, 1, B(SC88_MAP), false, 36, COMBO_TOGETHER },
	{ "the Native map ... holding down [SELECT] while you press [SC-55 MAP]",
	  "Puts every Part back on the Native map; the SC-55 Map indicator blinks.",
	  "All display (ALL lit)",
	  { B(SELECT) }, 1, B(SC55_MAP), false, 35, COMBO_HOLD_THEN_PRESS },
	{ "hold down the [SELECT] button and press the [SC-88MAP] button",
	  "Puts every Part on the SC-88 map; the SC-88 Map indicator blinks.",
	  "All display (ALL lit)",
	  { B(SELECT) }, 1, B(SC88_MAP), false, 35, COMBO_HOLD_THEN_PRESS },
	{ "Drum editing procedure",
	  "Enters and leaves Drum Edit, where each Drum Instrument of the set is edited by note name.",
	  "Part display",
	  { B(SELECT) }, 1, B(EDIT1_LEFT), false, 42, COMBO_TOGETHER },
	{ "switch between Drum Set select mode and Drum Instrument select mode",
	  "Toggles what the Instrument buttons step: the Drum Set, whose number blinks, or the Drum Instrument.",
	  "Drum Edit",
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, 43, COMBO_TOGETHER },

	/* Chapter 3 -- System Effects */
	{ "the current parameter value will be displayed graphically",
	  "Draws the reverb send level graphically; the same press returns to the normal display.",
	  "Part or All display",
	  { B(REVERB_LEFT) }, 1, B(REVERB_RIGHT), false, 50, COMBO_TOGETHER },
	{ "the current parameter value will be displayed graphically",
	  "Draws the chorus send level graphically; the same press returns to the normal display.",
	  "Part or All display",
	  { B(CHORUS_LEFT) }, 1, B(CHORUS_RIGHT), false, 50, COMBO_TOGETHER },
	{ "While holding the [SC-88MAP] button, press both [l][r] buttons of DELAY",
	  "Draws the delay send level graphically; the same press returns to the normal display.",
	  "Part or All display",
	  { B(SC88_MAP), B(KEY_SHIFT_LEFT) }, 2, B(KEY_SHIFT_RIGHT), false, 50, COMBO_HOLD_THEN_PAIR },
	{ "Simultaneously press both EFX TYPE [l][r]",
	  "Draws the delay send level graphically when the EFX indicator is dark and the edit row sets delay.",
	  "Part or All display (EFX dark)",
	  { B(EDIT1_LEFT) }, 1, B(EDIT1_RIGHT), false, 50, COMBO_TOGETHER },

	/* Chapter 5 -- Convenient functions */
	{ "Press [USER INST] and [SELECT] simultaneously, the indicator light red",
	  "Enters User Instrument edit, where the edit rows change the sound itself rather than the Part.",
	  "Part display",
	  { B(USER_INST) }, 1, B(SELECT), false, 97, COMBO_TOGETHER },
	{ "Simultaneously press [USER INST] and [SELECT]",
	  "Asks \"Write UI 64/001?\" to store the edited sound as a User Instrument.",
	  "User Instrument edit",
	  { B(USER_INST) }, 1, B(SELECT), false, 98, COMBO_TOGETHER },
	{ "Simultaneously pressing both INSTRUMENT [l] and [r] will move between the two numbers",
	  "Moves the cursor between the instrument number and the variation number in the Write prompt.",
	  "\"Write UI ...?\" prompt",
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, 98, COMBO_TOGETHER },
	{ "Simultaneously press [EFX] and [ON/OFF]",
	  "Asks \"Write U.EFX 01?\" to store the insertion effect settings as one of 64 User Effects.",
	  "EFX mode",
	  { B(USER_INST) }, 1, B(SELECT), false, 99, COMBO_TOGETHER },
	{ "Naming a User Patch",
	  "Enters and leaves Patch-name editing, where Part moves the cursor and Instrument picks the character.",
	  "All display (ALL lit)",
	  { B(PAN_RIGHT) }, 1, B(CHORUS_RIGHT), false, 100, COMBO_TOGETHER },
	{ "Saving a User Patch",
	  "Asks \"Write U.Patch01?\" to store Parts A01 and A02 and the common settings as User Patch U01-U16.",
	  "All display (ALL lit)",
	  { B(USER_INST) }, 1, B(SELECT), false, 101, COMBO_TOGETHER },
	{ "Naming a User Drum Set",
	  "Enters and leaves Drum-Set-name editing for the selected Drum Part.",
	  "Part display",
	  { B(PAN_RIGHT) }, 1, B(CHORUS_RIGHT), false, 102, COMBO_TOGETHER },
	{ "If you wish to change the User Drum Set number",
	  "Switches the Instrument buttons to selecting User Drum Set 65 or 66 while naming.",
	  "naming screen",
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, 102, COMBO_TOGETHER },
	{ "To store an individual Drum Instrument",
	  "Asks \"Write UD D#3/65?\" to store one Drum Instrument into a note of a User Drum Set.",
	  "Drum Edit",
	  { B(USER_INST) }, 1, B(SELECT), false, 104, COMBO_TOGETHER },
	{ "the cursor will move between the Note Name and the Drum Set number",
	  "Moves the cursor in the \"Write UD ...?\" prompt.",
	  "\"Write UD ...?\" prompt",
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, 104, COMBO_TOGETHER },
	{ "To store the entire Drum Set",
	  "Asks \"Write U.DRUM 65?\" to store all 128 Drum Instruments as User Drum Set 65 or 66.",
	  "Drum Edit",
	  { B(EDIT3_LEFT) }, 1, B(EDIT3_RIGHT), false, 105, COMBO_TOGETHER },
	{ "Copy",
	  "Asks \"Copy A01->A02?\" to copy the selected Part's settings to another Part.",
	  "Part display",
	  { B(SELECT) }, 1, B(LEVEL_LEFT), false, 106, COMBO_HOLD_THEN_PRESS },
	{ "Initialize",
	  "Asks \"Clear A01?\" to return the selected Part to its default settings.",
	  "Part display",
	  { B(SELECT) }, 1, B(LEVEL_RIGHT), false, 106, COMBO_HOLD_THEN_PRESS },
	{ "Exchange",
	  "Asks \"Exchg A01<->A02?\" to swap the settings of two Parts.",
	  "Part display",
	  { B(SELECT) }, 1, B(PAN_LEFT), false, 106, COMBO_HOLD_THEN_PRESS },
	{ "Bulk Dump procedure",
	  "Asks \"Dump ALL,Sure?\" to transmit the chosen block of memory as System Exclusive data.",
	  "All display (ALL lit)",
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, 107, COMBO_TOGETHER },
	{ "the data will be transmitted",
	  "Transmits the parameter shown in the menu as an Individual Data exclusive message.",
	  "any menu",
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, 108, COMBO_TOGETHER },
	{ "the Effect Type data will be transmitted",
	  "Transmits the displayed insertion-effect type or parameter as exclusive data.",
	  "EFX mode",
	  { B(EDIT3_LEFT) }, 1, B(EDIT3_RIGHT), false, 109, COMBO_TOGETHER },
	{ "Frame Draw",
	  "Enters and leaves Frame Draw, where the display's dots are drawn by hand over ten pages.",
	  NULL,
	  { B(EDIT1_RIGHT) }, 1, B(EDIT2_LEFT), false, 110, COMBO_TOGETHER },
	{ "to transmit the screen data to an external device",
	  "Sends the current Frame Draw page as exclusive data.",
	  "Frame Draw",
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, 110, COMBO_TOGETHER },
	{ "SC-88-compatibility mode",
	  "Turns SC-88-compatibility mode on, and off again; the All button blinks while it is on.",
	  NULL,
	  { B(SELECT) }, 1, B(ALL), false, 112, COMBO_HOLD_THEN_PRESS },
	{ "Selecting the CM-64 sound map",
	  "Asks \"Init CM-64, Sure?\" to switch the unit to the CM-64 sound map, losing every previous setting.",
	  NULL,
	  { B(SELECT) }, 1, B(INSTRUMENT_LEFT), false, 114, COMBO_HOLD_THEN_PRESS },
	{ "Selecting Double Module Mode",
	  "Asks \"Set Mode2, Sure?\" to split the unit into two GM/GS modules with their own system effects.",
	  NULL,
	  { B(SELECT) }, 1, B(KEY_SHIFT_RIGHT), false, 116, COMBO_HOLD_THEN_PRESS },
	{ "To return to Single Module Mode",
	  "Asks \"Set Mode1, Sure?\" to return to one 32-Part module.",
	  "Double Module Mode",
	  { B(SELECT) }, 1, B(KEY_SHIFT_LEFT), false, 116, COMBO_HOLD_THEN_PRESS },
	{ "Initialize all Parts to the factory settings",
	  "Asks \"Init All, Sure?\" to restore every setting, System and User parameters included.",
	  NULL,
	  { B(SELECT), B(INSTRUMENT_LEFT) }, 2, B(INSTRUMENT_RIGHT), false, 118, COMBO_HOLD_THEN_PAIR },
	{ "Initialize for GM",
	  "Asks \"Init GM, Sure?\" to set the unit to the basic GM state.",
	  NULL,
	  { B(SELECT) }, 1, B(PART_RIGHT), false, 118, COMBO_HOLD_THEN_PRESS },
	{ "Initialize for GS",
	  "Asks \"Init GS, Sure?\" to set the unit to the basic GS state.",
	  NULL,
	  { B(SELECT) }, 1, B(INSTRUMENT_RIGHT), false, 118, COMBO_HOLD_THEN_PRESS },

	/* Chapter 8 -- Appendix */
	{ "View settings for 32 Parts in the Part display",
	  "Shows all 32 Parts at once in the bar display.",
	  "Part display",
	  { B(EDIT2_RIGHT) }, 1, B(EDIT3_LEFT), false, 153, COMBO_TOGETHER },

	/* Service notes -- "TEST MODE / Switch operations", "IDENTIFYING VERSION NUMBER"
	 * (Roland SC-88Pro Service Notes, First Edition, Nov.1996, p.4 and p.8).  The `page`
	 * field below is that document's page, not the owner's manual's; docs/panel/combinations.md
	 * keeps the two apart.  The rear Select switch (MIDI / Mac / PC-1 / PC-2) that some of
	 * these depend on is not a panel button and cannot be set from here. */
	{ "Normal Test Mode",
	  "Rear Select SW on MIDI: held while switching on, then PREVIEW, enters the factory Test Mode at T-1.",
	  "power-on",
	  { B(KEY_SHIFT_LEFT), B(KEY_SHIFT_RIGHT) }, 2, B(PREVIEW), true, 4, COMBO_HOLD_THEN_PRESS },
	{ "Serial Test (4')",
	  "The same hold with the rear Select SW on Mac enters the Test Mode at the Serial Test instead.",
	  "power-on",
	  { B(KEY_SHIFT_LEFT), B(KEY_SHIFT_RIGHT) }, 2, B(PREVIEW), true, 4, COMBO_HOLD_THEN_PRESS },
	{ "THRU Check",
	  "Rear Select SW on MIDI: held while switching on, puts the unit in the MIDI THRU check.",
	  "power-on",
	  { B(REVERB_LEFT), B(CHORUS_RIGHT) }, 2, NONE, true, 4, COMBO_HOLD_THEN_PRESS },
	{ "Identifying version number",
	  "Held while switching on, then PREVIEW, shows the ROM, sub-CPU, SCGS-core and parameter versions.",
	  "power-on",
	  { B(MIDI_CH_LEFT), B(MIDI_CH_RIGHT) }, 2, B(PREVIEW), true, 8, COMBO_HOLD_THEN_PRESS },
	{ "To move to the next test.",
	  "In Test Mode, steps to the following test.",
	  "Test Mode",
	  { B(KEY_SHIFT_LEFT) }, 1, B(MIDI_CH_RIGHT), false, 4, COMBO_HOLD_THEN_PRESS },
	{ "To return to the preceding test.",
	  "In Test Mode, steps back to the previous test.",
	  "Test Mode",
	  { B(KEY_SHIFT_LEFT) }, 1, B(MIDI_CH_LEFT), false, 4, COMBO_HOLD_THEN_PRESS },
	{ "To perform the same test once again.",
	  "In Test Mode, restarts the test that is running.",
	  "Test Mode",
	  { B(KEY_SHIFT_LEFT) }, 1, B(PAN_RIGHT), false, 4, COMBO_HOLD_THEN_PRESS },
	{ "1. LCD & LED Test",
	  "In Test Mode, jumps to T-1, which lights every LCD dot and then every LED.",
	  "Test Mode",
	  { B(KEY_SHIFT_LEFT) }, 1, B(PART_LEFT), false, 4, COMBO_HOLD_THEN_PRESS },
	{ "2. Memory Test",
	  "In Test Mode, jumps to T-2, which checks PROM, SRAM, DRAM, the wave ROMs and the LSP chip.",
	  "Test Mode",
	  { B(KEY_SHIFT_LEFT) }, 1, B(PART_RIGHT), false, 4, COMBO_HOLD_THEN_PRESS },
	{ "3. Switch Test",
	  "In Test Mode, jumps to T-3, which names each panel switch as it is pressed.",
	  "Test Mode",
	  { B(KEY_SHIFT_LEFT) }, 1, B(INSTRUMENT_LEFT), false, 4, COMBO_HOLD_THEN_PRESS },
	{ "4. MIDI & Battery Test",
	  "In Test Mode, jumps to T-4, which reads the battery voltage and loops the MIDI ports.",
	  "Test Mode",
	  { B(KEY_SHIFT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, 4, COMBO_HOLD_THEN_PRESS },
	{ "5. Sound & Effect Test",
	  "In Test Mode, jumps to T-5, which walks the four outputs and the reverb, chorus and delay.",
	  "Test Mode",
	  { B(KEY_SHIFT_LEFT) }, 1, B(LEVEL_LEFT), false, 4, COMBO_HOLD_THEN_PRESS },
	{ "6. LSP Test",
	  "In Test Mode, jumps to T-6, the LSP test; the notes give no procedure for it.",
	  "Test Mode",
	  { B(KEY_SHIFT_LEFT) }, 1, B(LEVEL_RIGHT), false, 4, COMBO_HOLD_THEN_PRESS },
};

const int combo_count = (int)(sizeof combos / sizeof combos[0]);

int combos_for(scemu_button_t button, int *out, int max)
{
	int n = 0;

	for (int i = 0; i < combo_count; i++)
	{
		bool involved = combos[i].press == button;

		for (int j = 0; !involved && j < combos[i].hold_count; j++)
			if (combos[i].hold[j] == button)
				involved = true;
		if (!involved)
			continue;
		if (n < max && out)
			out[n] = i;
		n++;
	}
	return n > max ? max : n;
}

/* the panel's own words for a key */
static const char *const button_label[SCEMU_BUTTON_COUNT] = {
	[SCEMU_BUTTON_ALL] = "ALL", [SCEMU_BUTTON_MUTE] = "MUTE",
	[SCEMU_BUTTON_SC55_MAP] = "SC-55 MAP", [SCEMU_BUTTON_SC88_MAP] = "SC-88 MAP",
	[SCEMU_BUTTON_PREVIEW] = "PREVIEW (push the knob)",
	[SCEMU_BUTTON_PART_LEFT] = "PART ◀", [SCEMU_BUTTON_PART_RIGHT] = "PART ▶",
	[SCEMU_BUTTON_INSTRUMENT_LEFT] = "INSTRUMENT ◀", [SCEMU_BUTTON_INSTRUMENT_RIGHT] = "INSTRUMENT ▶",
	[SCEMU_BUTTON_LEVEL_LEFT] = "LEVEL ◀", [SCEMU_BUTTON_LEVEL_RIGHT] = "LEVEL ▶",
	[SCEMU_BUTTON_PAN_LEFT] = "PAN ◀", [SCEMU_BUTTON_PAN_RIGHT] = "PAN ▶",
	[SCEMU_BUTTON_REVERB_LEFT] = "REVERB ◀", [SCEMU_BUTTON_REVERB_RIGHT] = "REVERB ▶",
	[SCEMU_BUTTON_CHORUS_LEFT] = "CHORUS ◀", [SCEMU_BUTTON_CHORUS_RIGHT] = "CHORUS ▶",
	[SCEMU_BUTTON_KEY_SHIFT_LEFT] = "KEY SHIFT/DELAY ◀", [SCEMU_BUTTON_KEY_SHIFT_RIGHT] = "KEY SHIFT/DELAY ▶",
	[SCEMU_BUTTON_MIDI_CH_LEFT] = "MIDI CH ◀", [SCEMU_BUTTON_MIDI_CH_RIGHT] = "MIDI CH ▶",
	[SCEMU_BUTTON_USER_INST] = "USER INST/EFX", [SCEMU_BUTTON_SELECT] = "SELECT/EFX ON/OFF",
	[SCEMU_BUTTON_EDIT1_LEFT] = "VIB RATE·ATTACK·EFX TYPE ◀", [SCEMU_BUTTON_EDIT1_RIGHT] = "VIB RATE·ATTACK·EFX TYPE ▶",
	[SCEMU_BUTTON_EDIT2_LEFT] = "VIB DEPTH·CUTOFF·DECAY·EFX PARAM ◀", [SCEMU_BUTTON_EDIT2_RIGHT] = "VIB DEPTH·CUTOFF·DECAY·EFX PARAM ▶",
	[SCEMU_BUTTON_EDIT3_LEFT] = "VIB DELAY·RESONANCE·RELEASE·EFX VALUE ◀", [SCEMU_BUTTON_EDIT3_RIGHT] = "VIB DELAY·RESONANCE·RELEASE·EFX VALUE ▶",
};

void combo_text(const combo_t *c, char *out, size_t size)
{
	bool together = c->timing == COMBO_TOGETHER && !c->power_on;
	int first = c->timing == COMBO_HOLD_THEN_PAIR && !c->power_on ? 1 : c->hold_count;
	size_t n = (size_t)snprintf(out, size, together ? "press " : "hold ");
	for (int k = 0; k < first && n < size; k++)
		n += (size_t)snprintf(out + n, size - n, "%s%s", k ? " + " : "", button_label[c->hold[k]]);
	if (c->power_on && n < size)
		n += (size_t)snprintf(out + n, size - n, " while switching on");
	if (c->press == SCEMU_BUTTON_COUNT)
		return;
	if (!together && n < size)
		n += (size_t)snprintf(out + n, size - n, ", then press ");
	for (int k = first; k < c->hold_count && n < size; k++)
		n += (size_t)snprintf(out + n, size - n, "%s + ", button_label[c->hold[k]]);
	if (n < size)
		n += (size_t)snprintf(out + n, size - n, "%s%s", together ? " + " : "", button_label[c->press]);
	if ((together || first < c->hold_count) && n < size)
		snprintf(out + n, size - n, " together");
}
