/* scemu GUI: the front-panel button combinations each model understands.
 *
 * Copyright (c) 2026 ian karlsson
 * SPDX-License-Identifier: BSD-3-Clause
 */
#include <stdio.h>
#include "combos.h"

/* The service notes' Test Mode -- the chord that enters it and the menu of tests inside it.
   Nothing here answers them yet, so a machine's menu would list a dozen rows that do nothing;
   set this to 1 to have them back, or hang a setting on it when the tests run. */
#define COMBOS_TEST_MODE 0

#define B(x) SCEMU_BUTTON_##x
#define NONE SCEMU_BUTTON_COUNT
#define P(x) PANEL_MODEL_##x

const combo_t combos[] = {
	/* ================================================================ SC-88Pro */
	/* Chapter 1 -- Try out the unit */
	{ "the value will change faster",
	  "Holding one half of the Part pair and pressing the other steps the Part number quickly.",
	  NULL, P(SC88PRO),
	  { B(PART_LEFT) }, 1, B(PART_RIGHT), false, "manual p.6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Instrument pair and pressing the other steps the sound quickly.",
	  NULL, P(SC88PRO),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Level pair and pressing the other changes the level quickly.",
	  NULL, P(SC88PRO),
	  { B(LEVEL_LEFT) }, 1, B(LEVEL_RIGHT), false, "manual p.6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Pan pair and pressing the other changes the pan quickly.",
	  NULL, P(SC88PRO),
	  { B(PAN_LEFT) }, 1, B(PAN_RIGHT), false, "manual p.6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Reverb pair and pressing the other changes the reverb level quickly.",
	  NULL, P(SC88PRO),
	  { B(REVERB_LEFT) }, 1, B(REVERB_RIGHT), false, "manual p.6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Chorus pair and pressing the other changes the chorus level quickly.",
	  NULL, P(SC88PRO),
	  { B(CHORUS_LEFT) }, 1, B(CHORUS_RIGHT), false, "manual p.6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Key Shift pair and pressing the other transposes quickly.",
	  NULL, P(SC88PRO),
	  { B(KEY_SHIFT_LEFT) }, 1, B(KEY_SHIFT_RIGHT), false, "manual p.6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the MIDI Channel pair and pressing the other steps the channel quickly.",
	  NULL, P(SC88PRO),
	  { B(MIDI_CH_LEFT) }, 1, B(MIDI_CH_RIGHT), false, "manual p.6", COMBO_HOLD_THEN_PRESS },
	{ "Adjust the amount of delay",
	  "Lowers the delay send level of the Part, or of all Parts when the ALL indicator is lit.",
	  "Part or All display", P(SC88PRO),
	  { B(SC88_MAP) }, 1, B(KEY_SHIFT_LEFT), false, "manual p.13", COMBO_HOLD_THEN_PRESS },
	{ "Adjust the amount of delay",
	  "Raises the delay send level of the Part, or of all Parts when the ALL indicator is lit.",
	  "Part or All display", P(SC88PRO),
	  { B(SC88_MAP) }, 1, B(KEY_SHIFT_RIGHT), false, "manual p.13", COMBO_HOLD_THEN_PRESS },

	/* Chapter 2 -- Parts and parameters */
	{ "To switch between the group A and B",
	  "Flips the Part display between Parts A01-A16 and Parts B01-B16.",
	  "Part display", P(SC88PRO),
	  { B(ALL) }, 1, B(PART_LEFT), false, "manual p.18", COMBO_TOGETHER },
	{ "Variation select mode",
	  "Enters and leaves Variation select, where the Instrument buttons pick the Variation number.",
	  "Part display", P(SC88PRO),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.20", COMBO_TOGETHER },
	{ "To switch between the A and B",
	  "Flips the Part's MIDI channel display between group A and group B channels.",
	  "Part display", P(SC88PRO),
	  { B(KEY_SHIFT_RIGHT) }, 1, B(MIDI_CH_LEFT), false, "manual p.22", COMBO_TOGETHER },
	{ "Part Monitor",
	  "Listens to the selected Part alone; the Mute indicator blinks while the monitor is on.",
	  "Part display", P(SC88PRO),
	  { B(ALL) }, 1, B(MUTE), false, "manual p.25", COMBO_TOGETHER },
	{ "the current setting will be shown graphically",
	  "Draws the Level of every Part as bars; the same press returns to the normal display.",
	  "Part or All display", P(SC88PRO),
	  { B(LEVEL_LEFT) }, 1, B(LEVEL_RIGHT), false, "manual p.25", COMBO_TOGETHER },
	{ "the current setting will be shown graphically",
	  "Draws Pan graphically; the same press returns to the normal display.",
	  "Part or All display", P(SC88PRO),
	  { B(PAN_LEFT) }, 1, B(PAN_RIGHT), false, "manual p.25", COMBO_TOGETHER },
	{ "the current setting will be shown graphically",
	  "Draws Key Shift graphically; the same press returns to the normal display.",
	  "Part or All display", P(SC88PRO),
	  { B(KEY_SHIFT_LEFT) }, 1, B(KEY_SHIFT_RIGHT), false, "manual p.25", COMBO_TOGETHER },
	{ "Parameters that must be selected from the menu",
	  "Opens and closes the per-Part parameter menu, from Part EQ to the CC1 LFO block.",
	  "Part display", P(SC88PRO),
	  { B(PART_LEFT) }, 1, B(PART_RIGHT), false, "manual p.26", COMBO_TOGETHER },
	{ "Parameter jump",
	  "Skips the menu cursor up to the head of the next parameter block.",
	  "any menu", P(SC88PRO),
	  { B(SELECT) }, 1, B(SC55_MAP), false, "manual p.26", COMBO_HOLD_THEN_PRESS },
	{ "Parameter jump",
	  "Skips the menu cursor down to the head of the next parameter block.",
	  "any menu", P(SC88PRO),
	  { B(SELECT) }, 1, B(SC88_MAP), false, "manual p.26", COMBO_HOLD_THEN_PRESS },
	{ "setting status ... graphically",
	  "Draws Vibrato Rate, Attack Time or the EFX type row graphically; the same press returns.",
	  "Part display", P(SC88PRO),
	  { B(EDIT1_LEFT) }, 1, B(EDIT1_RIGHT), false, "manual p.31", COMBO_TOGETHER },
	{ "setting status ... graphically",
	  "Draws Vibrato Depth, Cutoff or Decay graphically; the same press returns.",
	  "Part display", P(SC88PRO),
	  { B(EDIT2_LEFT) }, 1, B(EDIT2_RIGHT), false, "manual p.31", COMBO_TOGETHER },
	{ "setting status ... graphically",
	  "Draws Vibrato Delay, Resonance or Release graphically; the same press returns.",
	  "Part display", P(SC88PRO),
	  { B(EDIT3_LEFT) }, 1, B(EDIT3_RIGHT), false, "manual p.31", COMBO_TOGETHER },
	{ "Setting parameters common to all Parts",
	  "Opens and closes the all-Parts menu: M. Tune, the system effects, EFX control, Device ID and the receive switches.",
	  "All display (ALL lit)", P(SC88PRO),
	  { B(PART_LEFT) }, 1, B(PART_RIGHT), false, "manual p.14", COMBO_TOGETHER },
	{ "System parameter settings",
	  "Opens and closes the System-parameter menu, from Preview Note to Patch Load Initialize.",
	  NULL, P(SC88PRO),
	  { B(SC55_MAP) }, 1, B(SC88_MAP), false, "manual p.36", COMBO_TOGETHER },
	{ "the Native map ... holding down [SELECT] while you press [SC-55 MAP]",
	  "Puts every Part back on the Native map; the SC-55 Map indicator blinks.",
	  "All display (ALL lit)", P(SC88PRO),
	  { B(SELECT) }, 1, B(SC55_MAP), false, "manual p.35", COMBO_HOLD_THEN_PRESS },
	{ "hold down the [SELECT] button and press the [SC-88MAP] button",
	  "Puts every Part on the SC-88 map; the SC-88 Map indicator blinks.",
	  "All display (ALL lit)", P(SC88PRO),
	  { B(SELECT) }, 1, B(SC88_MAP), false, "manual p.35", COMBO_HOLD_THEN_PRESS },
	{ "Drum editing procedure",
	  "Enters and leaves Drum Edit, where each Drum Instrument of the set is edited by note name.",
	  "Part display", P(SC88PRO),
	  { B(SELECT) }, 1, B(EDIT1_LEFT), false, "manual p.42", COMBO_TOGETHER },
	{ "switch between Drum Set select mode and Drum Instrument select mode",
	  "Toggles what the Instrument buttons step: the Drum Set, whose number blinks, or the Drum Instrument.",
	  "Drum Edit", P(SC88PRO),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.43", COMBO_TOGETHER },

	/* Chapter 3 -- System Effects */
	{ "the current parameter value will be displayed graphically",
	  "Draws the reverb send level graphically; the same press returns to the normal display.",
	  "Part or All display", P(SC88PRO),
	  { B(REVERB_LEFT) }, 1, B(REVERB_RIGHT), false, "manual p.50", COMBO_TOGETHER },
	{ "the current parameter value will be displayed graphically",
	  "Draws the chorus send level graphically; the same press returns to the normal display.",
	  "Part or All display", P(SC88PRO),
	  { B(CHORUS_LEFT) }, 1, B(CHORUS_RIGHT), false, "manual p.50", COMBO_TOGETHER },
	{ "While holding the [SC-88MAP] button, press both [l][r] buttons of DELAY",
	  "Draws the delay send level graphically; the same press returns to the normal display.",
	  "Part or All display", P(SC88PRO),
	  { B(SC88_MAP), B(KEY_SHIFT_LEFT) }, 2, B(KEY_SHIFT_RIGHT), false, "manual p.50", COMBO_HOLD_THEN_PAIR },
	{ "Simultaneously press both EFX TYPE [l][r]",
	  "Draws the delay send level graphically when the EFX indicator is dark and the edit row sets delay.",
	  "Part or All display (EFX dark)", P(SC88PRO),
	  { B(EDIT1_LEFT) }, 1, B(EDIT1_RIGHT), false, "manual p.50", COMBO_TOGETHER },

	/* Chapter 5 -- Convenient functions */
	{ "Press [USER INST] and [SELECT] simultaneously, the indicator light red",
	  "Enters User Instrument edit, where the edit rows change the sound itself rather than the Part.",
	  "Part display", P(SC88PRO),
	  { B(USER_INST) }, 1, B(SELECT), false, "manual p.97", COMBO_TOGETHER },
	{ "Simultaneously press [USER INST] and [SELECT]",
	  "Asks \"Write UI 64/001?\" to store the edited sound as a User Instrument.",
	  "User Instrument edit", P(SC88PRO),
	  { B(USER_INST) }, 1, B(SELECT), false, "manual p.98", COMBO_TOGETHER },
	{ "Simultaneously pressing both INSTRUMENT [l] and [r] will move between the two numbers",
	  "Moves the cursor between the instrument number and the variation number in the Write prompt.",
	  "\"Write UI ...?\" prompt", P(SC88PRO),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.98", COMBO_TOGETHER },
	{ "Simultaneously press [EFX] and [ON/OFF]",
	  "Asks \"Write U.EFX 01?\" to store the insertion effect settings as one of 64 User Effects.",
	  "EFX mode", P(SC88PRO),
	  { B(USER_INST) }, 1, B(SELECT), false, "manual p.99", COMBO_TOGETHER },
	{ "Naming a User Patch",
	  "Enters and leaves Patch-name editing, where Part moves the cursor and Instrument picks the character.",
	  "All display (ALL lit)", P(SC88PRO),
	  { B(PAN_RIGHT) }, 1, B(CHORUS_RIGHT), false, "manual p.100", COMBO_TOGETHER },
	{ "Saving a User Patch",
	  "Asks \"Write U.Patch01?\" to store Parts A01 and A02 and the common settings as User Patch U01-U16.",
	  "All display (ALL lit)", P(SC88PRO),
	  { B(USER_INST) }, 1, B(SELECT), false, "manual p.101", COMBO_TOGETHER },
	{ "Naming a User Drum Set",
	  "Enters and leaves Drum-Set-name editing for the selected Drum Part.",
	  "Part display", P(SC88PRO),
	  { B(PAN_RIGHT) }, 1, B(CHORUS_RIGHT), false, "manual p.102", COMBO_TOGETHER },
	{ "If you wish to change the User Drum Set number",
	  "Switches the Instrument buttons to selecting User Drum Set 65 or 66 while naming.",
	  "naming screen", P(SC88PRO),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.102", COMBO_TOGETHER },
	{ "To store an individual Drum Instrument",
	  "Asks \"Write UD D#3/65?\" to store one Drum Instrument into a note of a User Drum Set.",
	  "Drum Edit", P(SC88PRO),
	  { B(USER_INST) }, 1, B(SELECT), false, "manual p.104", COMBO_TOGETHER },
	{ "the cursor will move between the Note Name and the Drum Set number",
	  "Moves the cursor in the \"Write UD ...?\" prompt.",
	  "\"Write UD ...?\" prompt", P(SC88PRO),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.104", COMBO_TOGETHER },
	{ "To store the entire Drum Set",
	  "Asks \"Write U.DRUM 65?\" to store all 128 Drum Instruments as User Drum Set 65 or 66.",
	  "Drum Edit", P(SC88PRO),
	  { B(EDIT3_LEFT) }, 1, B(EDIT3_RIGHT), false, "manual p.105", COMBO_TOGETHER },
	{ "Copy",
	  "Asks \"Copy A01->A02?\" to copy the selected Part's settings to another Part.",
	  "Part display", P(SC88PRO),
	  { B(SELECT) }, 1, B(LEVEL_LEFT), false, "manual p.106", COMBO_HOLD_THEN_PRESS },
	{ "Initialize",
	  "Asks \"Clear A01?\" to return the selected Part to its default settings.",
	  "Part display", P(SC88PRO),
	  { B(SELECT) }, 1, B(LEVEL_RIGHT), false, "manual p.106", COMBO_HOLD_THEN_PRESS },
	{ "Exchange",
	  "Asks \"Exchg A01<->A02?\" to swap the settings of two Parts.",
	  "Part display", P(SC88PRO),
	  { B(SELECT) }, 1, B(PAN_LEFT), false, "manual p.106", COMBO_HOLD_THEN_PRESS },
	{ "Bulk Dump procedure",
	  "Asks \"Dump ALL,Sure?\" to transmit the chosen block of memory as System Exclusive data.",
	  "All display (ALL lit)", P(SC88PRO),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.107", COMBO_TOGETHER },
	{ "the data will be transmitted",
	  "Transmits the parameter shown in the menu as an Individual Data exclusive message.",
	  "any menu", P(SC88PRO),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.108", COMBO_TOGETHER },
	{ "the Effect Type data will be transmitted",
	  "Transmits the displayed insertion-effect type or parameter as exclusive data.",
	  "EFX mode", P(SC88PRO),
	  { B(EDIT3_LEFT) }, 1, B(EDIT3_RIGHT), false, "manual p.109", COMBO_TOGETHER },
	{ "Frame Draw",
	  "Enters and leaves Frame Draw, where the display's dots are drawn by hand over ten pages.",
	  NULL, P(SC88PRO),
	  { B(EDIT1_RIGHT) }, 1, B(EDIT2_LEFT), false, "manual p.110", COMBO_TOGETHER },
	{ "to transmit the screen data to an external device",
	  "Sends the current Frame Draw page as exclusive data.",
	  "Frame Draw", P(SC88PRO),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.110", COMBO_TOGETHER },
	{ "SC-88-compatibility mode",
	  "Turns SC-88-compatibility mode on, and off again; the All button blinks while it is on.",
	  NULL, P(SC88PRO),
	  { B(SELECT) }, 1, B(ALL), false, "manual p.112", COMBO_HOLD_THEN_PRESS },
	{ "Selecting the CM-64 sound map",
	  "Asks \"Init CM-64, Sure?\" to switch the unit to the CM-64 sound map, losing every previous setting.",
	  NULL, P(SC88PRO),
	  { B(SELECT) }, 1, B(INSTRUMENT_LEFT), false, "manual p.114", COMBO_HOLD_THEN_PRESS },
	{ "Selecting Double Module Mode",
	  "Asks \"Set Mode2, Sure?\" to split the unit into two GM/GS modules with their own system effects.",
	  NULL, P(SC88PRO),
	  { B(SELECT) }, 1, B(KEY_SHIFT_RIGHT), false, "manual p.116", COMBO_HOLD_THEN_PRESS },
	{ "To return to Single Module Mode",
	  "Asks \"Set Mode1, Sure?\" to return to one 32-Part module.",
	  "Double Module Mode", P(SC88PRO),
	  { B(SELECT) }, 1, B(KEY_SHIFT_LEFT), false, "manual p.116", COMBO_HOLD_THEN_PRESS },
	{ "Initialize all Parts to the factory settings",
	  "Asks \"Init All, Sure?\" to restore every setting, System and User parameters included.",
	  NULL, P(SC88PRO),
	  { B(SELECT), B(INSTRUMENT_LEFT) }, 2, B(INSTRUMENT_RIGHT), false, "manual p.118", COMBO_HOLD_THEN_PAIR },
	{ "Initialize for GM",
	  "Asks \"Init GM, Sure?\" to set the unit to the basic GM state.",
	  NULL, P(SC88PRO),
	  { B(SELECT) }, 1, B(PART_RIGHT), false, "manual p.118", COMBO_HOLD_THEN_PRESS },
	{ "Initialize for GS",
	  "Asks \"Init GS, Sure?\" to set the unit to the basic GS state.",
	  NULL, P(SC88PRO),
	  { B(SELECT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.118", COMBO_HOLD_THEN_PRESS },

	/* Chapter 8 -- Appendix */
	{ "View settings for 32 Parts in the Part display",
	  "Shows all 32 Parts at once in the bar display.",
	  "Part display", P(SC88PRO),
	  { B(EDIT2_RIGHT) }, 1, B(EDIT3_LEFT), false, "manual p.153", COMBO_TOGETHER },

	/* Service notes -- "TEST MODE / Switch operations", "IDENTIFYING VERSION NUMBER"
	 * (Roland SC-88Pro Service Notes, First Edition, Nov.1996, p.4 and p.8).  The rear Select
	 * switch (MIDI / Mac / PC-1 / PC-2) that some of these depend on is not a panel button and
	 * cannot be set from here. */
#if COMBOS_TEST_MODE
	{ "Normal Test Mode",
	  "Rear Select SW on MIDI: held while switching on, then PREVIEW, enters the factory Test Mode at T-1.",
	  "power-on", P(SC88PRO),
	  { B(KEY_SHIFT_LEFT), B(KEY_SHIFT_RIGHT) }, 2, B(PREVIEW), true, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "Serial Test (4')",
	  "The same hold with the rear Select SW on Mac enters the Test Mode at the Serial Test instead.",
	  "power-on", P(SC88PRO),
	  { B(KEY_SHIFT_LEFT), B(KEY_SHIFT_RIGHT) }, 2, B(PREVIEW), true, "service notes p.4", COMBO_HOLD_THEN_PRESS },
#endif
	{ "THRU Check",
	  "Rear Select SW on MIDI: held while switching on, puts the unit in the MIDI THRU check.",
	  "power-on", P(SC88PRO),
	  { B(REVERB_LEFT), B(CHORUS_RIGHT) }, 2, NONE, true, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "Identifying version number",
	  "Held while switching on, then PREVIEW, shows the ROM, sub-CPU, SCGS-core and parameter versions.",
	  "power-on", P(SC88PRO),
	  { B(MIDI_CH_LEFT), B(MIDI_CH_RIGHT) }, 2, B(PREVIEW), true, "service notes p.8", COMBO_HOLD_THEN_PRESS },
#if COMBOS_TEST_MODE
	{ "To move to the next test.",
	  "In Test Mode, steps to the following test.",
	  "Test Mode", P(SC88PRO),
	  { B(KEY_SHIFT_LEFT) }, 1, B(MIDI_CH_RIGHT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "To return to the preceding test.",
	  "In Test Mode, steps back to the previous test.",
	  "Test Mode", P(SC88PRO),
	  { B(KEY_SHIFT_LEFT) }, 1, B(MIDI_CH_LEFT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "To perform the same test once again.",
	  "In Test Mode, restarts the test that is running.",
	  "Test Mode", P(SC88PRO),
	  { B(KEY_SHIFT_LEFT) }, 1, B(PAN_RIGHT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "1. LCD & LED Test",
	  "In Test Mode, jumps to T-1, which lights every LCD dot and then every LED.",
	  "Test Mode", P(SC88PRO),
	  { B(KEY_SHIFT_LEFT) }, 1, B(PART_LEFT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "2. Memory Test",
	  "In Test Mode, jumps to T-2, which checks PROM, SRAM, DRAM, the wave ROMs and the LSP chip.",
	  "Test Mode", P(SC88PRO),
	  { B(KEY_SHIFT_LEFT) }, 1, B(PART_RIGHT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "3. Switch Test",
	  "In Test Mode, jumps to T-3, which names each panel switch as it is pressed.",
	  "Test Mode", P(SC88PRO),
	  { B(KEY_SHIFT_LEFT) }, 1, B(INSTRUMENT_LEFT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "4. MIDI & Battery Test",
	  "In Test Mode, jumps to T-4, which reads the battery voltage and loops the MIDI ports.",
	  "Test Mode", P(SC88PRO),
	  { B(KEY_SHIFT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "5. Sound & Effect Test",
	  "In Test Mode, jumps to T-5, which walks the four outputs and the reverb, chorus and delay.",
	  "Test Mode", P(SC88PRO),
	  { B(KEY_SHIFT_LEFT) }, 1, B(LEVEL_LEFT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "6. LSP Test",
	  "In Test Mode, jumps to T-6, the LSP test; the notes give no procedure for it.",
	  "Test Mode", P(SC88PRO),
	  { B(KEY_SHIFT_LEFT) }, 1, B(LEVEL_RIGHT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
#endif

	/* ================================================================ SC-88
	 * Owner's manual "SC-88_e2"; its pages are numbered by chapter, and the "Parameter list and
	 * operations" appendix (p.7-6 to 7-9) is the spine.  The three edit pairs on the lower face
	 * are printed DELAY, INSTRUMENT and VARIATION, so the manual's "INSTRUMENT [l][r]" is the
	 * middle edit pair wherever it sets a sound parameter and the block's own pair everywhere
	 * else; the fourth strip key is EQ, the Pro's SC-88 MAP position. */
	{ "the value will change faster",
	  "Holding one half of the Part pair and pressing the other steps the Part number quickly.",
	  NULL, P(SC88),
	  { B(PART_LEFT) }, 1, B(PART_RIGHT), false, "manual p.0-6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Instrument pair and pressing the other steps the sound quickly.",
	  NULL, P(SC88),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.0-6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Level pair and pressing the other changes the level quickly.",
	  NULL, P(SC88),
	  { B(LEVEL_LEFT) }, 1, B(LEVEL_RIGHT), false, "manual p.0-6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Pan pair and pressing the other changes the pan quickly.",
	  NULL, P(SC88),
	  { B(PAN_LEFT) }, 1, B(PAN_RIGHT), false, "manual p.0-6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Reverb pair and pressing the other changes the reverb level quickly.",
	  NULL, P(SC88),
	  { B(REVERB_LEFT) }, 1, B(REVERB_RIGHT), false, "manual p.0-6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Chorus pair and pressing the other changes the chorus level quickly.",
	  NULL, P(SC88),
	  { B(CHORUS_LEFT) }, 1, B(CHORUS_RIGHT), false, "manual p.0-6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Key Shift pair and pressing the other transposes quickly.",
	  NULL, P(SC88),
	  { B(KEY_SHIFT_LEFT) }, 1, B(KEY_SHIFT_RIGHT), false, "manual p.0-6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the MIDI Channel pair and pressing the other steps the channel quickly.",
	  NULL, P(SC88),
	  { B(MIDI_CH_LEFT) }, 1, B(MIDI_CH_RIGHT), false, "manual p.0-6", COMBO_HOLD_THEN_PRESS },

	{ "To switch between the A and B Parts",
	  "Flips the Part display between Parts A01-A16 and Parts B01-B16.",
	  "Part display", P(SC88),
	  { B(ALL) }, 1, B(PART_LEFT), false, "manual p.2-2", COMBO_TOGETHER },
	{ "Select a Variation sound",
	  "Enters and leaves Variation select, where the Instrument buttons pick the Variation number.",
	  "Part display", P(SC88),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.1-5", COMBO_TOGETHER },
	{ "To switch between the A and B",
	  "Flips the Part's MIDI channel display between group A and group B channels.",
	  "Part display", P(SC88),
	  { B(KEY_SHIFT_RIGHT) }, 1, B(MIDI_CH_LEFT), false, "manual p.2-7", COMBO_TOGETHER },
	{ "PART Monitor",
	  "Listens to the selected Part alone.",
	  "Part display", P(SC88),
	  { B(ALL) }, 1, B(MUTE), false, "manual p.2-10", COMBO_TOGETHER },
	{ "Individual Part settings",
	  "Opens and closes the per-Part parameter menu, from Part Mode to the Channel Aftertouch block.",
	  "Part display (ALL dark)", P(SC88),
	  { B(PART_LEFT) }, 1, B(PART_RIGHT), false, "manual p.2-11", COMBO_TOGETHER },
	{ "Overall Part settings",
	  "Opens and closes the all-Parts menu: Master Tune, the system effects and the receive switches.",
	  "All display (ALL lit)", P(SC88),
	  { B(PART_LEFT) }, 1, B(PART_RIGHT), false, "manual p.1-8", COMBO_TOGETHER },
	{ "graphically display the current setting",
	  "Draws the Level of every Part as bars; the same press returns to the normal display.",
	  "Part or All display", P(SC88),
	  { B(LEVEL_LEFT) }, 1, B(LEVEL_RIGHT), false, "manual p.2-21", COMBO_TOGETHER },
	{ "graphically display the current setting",
	  "Draws Pan graphically; the same press returns to the normal display.",
	  "Part or All display", P(SC88),
	  { B(PAN_LEFT) }, 1, B(PAN_RIGHT), false, "manual p.2-21", COMBO_TOGETHER },
	{ "graphically display the current setting",
	  "Draws Key Shift graphically; the same press returns to the normal display.",
	  "Part or All display", P(SC88),
	  { B(KEY_SHIFT_LEFT) }, 1, B(KEY_SHIFT_RIGHT), false, "manual p.2-21", COMBO_TOGETHER },
	{ "the setting status of that parameter ... graphically",
	  "Draws Vibrato Rate, Filter Cutoff or Attack Time graphically; the same press returns.",
	  "Part display", P(SC88),
	  { B(EDIT1_LEFT) }, 1, B(EDIT1_RIGHT), false, "manual p.2-17", COMBO_TOGETHER },
	{ "the setting status of that parameter ... graphically",
	  "Draws Vibrato Depth, Cutoff or Decay graphically; the same press returns.",
	  "Part display", P(SC88),
	  { B(EDIT2_LEFT) }, 1, B(EDIT2_RIGHT), false, "manual p.2-17", COMBO_TOGETHER },
	{ "the setting status of that parameter ... graphically",
	  "Draws Vibrato Delay, Resonance or Release graphically; the same press returns.",
	  "Part display", P(SC88),
	  { B(EDIT3_LEFT) }, 1, B(EDIT3_RIGHT), false, "manual p.2-17", COMBO_TOGETHER },
	{ "the current parameter values ... displayed graphically",
	  "Draws the reverb send level graphically; the same press returns to the normal display.",
	  "Part or All display", P(SC88),
	  { B(REVERB_LEFT) }, 1, B(REVERB_RIGHT), false, "manual p.3-4", COMBO_TOGETHER },
	{ "the current parameter values ... displayed graphically",
	  "Draws the chorus send level graphically; the same press returns to the normal display.",
	  "Part or All display", P(SC88),
	  { B(CHORUS_LEFT) }, 1, B(CHORUS_RIGHT), false, "manual p.3-4", COMBO_TOGETHER },
	{ "the current parameter values ... displayed graphically",
	  "Draws the delay send level graphically; the same press returns to the normal display.",
	  "Part or All display", P(SC88),
	  { B(EDIT1_LEFT) }, 1, B(EDIT1_RIGHT), false, "manual p.3-4", COMBO_TOGETHER },
	{ "System functions",
	  "Opens and closes the System-parameter menu, from Preview Note to the Backup switch.",
	  NULL, P(SC88),
	  { B(SC55_MAP) }, 1, B(SC88_MAP), false, "manual p.2-24", COMBO_TOGETHER },
	{ "Drum editing procedure",
	  "Enters and leaves Drum Edit, where each Drum Instrument of the set is edited by note name.",
	  "Part display", P(SC88),
	  { B(SELECT) }, 1, B(EDIT1_LEFT), false, "manual p.2-28", COMBO_TOGETHER },
	{ "switch between Drum Set select mode and Drum Instrument select mode",
	  "Toggles what the Instrument buttons step: the Drum Set or the Drum Instrument.",
	  "Drum Edit", P(SC88),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.2-29", COMBO_TOGETHER },
	{ "User Instrument edit",
	  "Asks for the destination Instrument number to store the edited sound as a User Instrument.",
	  "User Instrument edit", P(SC88),
	  { B(USER_INST) }, 1, B(SELECT), false, "manual p.4-2", COMBO_TOGETHER },
	{ "set storing destination Variation number",
	  "Moves the cursor between the instrument number and the variation number in the Write prompt.",
	  "Write prompt", P(SC88),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.4-2", COMBO_TOGETHER },
	{ "To store an individual Drum Instrument",
	  "Asks for the note and User Drum Set to store one Drum Instrument into.",
	  "Drum Edit", P(SC88),
	  { B(USER_INST) }, 1, B(SELECT), false, "manual p.4-6", COMBO_TOGETHER },
	{ "set storing destination User Drum Set number",
	  "Moves the cursor between the Note number and the User Drum Set number in the Write prompt.",
	  "Write prompt", P(SC88),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.4-6", COMBO_TOGETHER },
	{ "To store an entire Drum Set",
	  "Asks for the User Drum Set, 65 or 66, to store all 128 Drum Instruments into.",
	  "Drum Edit", P(SC88),
	  { B(EDIT3_LEFT) }, 1, B(EDIT3_RIGHT), false, "manual p.4-7", COMBO_TOGETHER },
	{ "Name a Drum Set",
	  "Enters and leaves Drum-Set-name editing for the selected Drum Part.",
	  "Part display (ALL dark)", P(SC88),
	  { B(PAN_RIGHT) }, 1, B(CHORUS_RIGHT), false, "manual p.4-8", COMBO_TOGETHER },
	{ "Set a display name",
	  "Enters and leaves editing of the name the display shows, character by character.",
	  "All display (ALL lit)", P(SC88),
	  { B(PAN_RIGHT) }, 1, B(CHORUS_RIGHT), false, "manual p.4-9", COMBO_TOGETHER },
	{ "Bulk dump",
	  "Asks which block of memory to transmit as System Exclusive data.",
	  "All display (ALL lit)", P(SC88),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.4-10", COMBO_TOGETHER },
	{ "View settings for 32 Parts in the Part display",
	  "Shows all 32 Parts at once in the bar display.",
	  "Part display", P(SC88),
	  { B(EDIT2_RIGHT) }, 1, B(EDIT3_LEFT), false, "manual p.7-9", COMBO_TOGETHER },
	{ "Single Module mode",
	  "Asks to return to one 32-Part module.",
	  NULL, P(SC88),
	  { B(SELECT) }, 1, B(KEY_SHIFT_LEFT), false, "manual p.4-16", COMBO_HOLD_THEN_PRESS },
	{ "Double Module mode",
	  "Asks to split the unit into two GM/GS modules with their own system effects.",
	  NULL, P(SC88),
	  { B(SELECT) }, 1, B(KEY_SHIFT_RIGHT), false, "manual p.4-16", COMBO_HOLD_THEN_PRESS },
	{ "Reset to factory settings",
	  "Asks to restore every setting, System and User parameters included.",
	  NULL, P(SC88),
	  { B(SELECT), B(INSTRUMENT_LEFT) }, 2, B(INSTRUMENT_RIGHT), false, "manual p.4-18", COMBO_HOLD_THEN_PAIR },
	{ "Initialize for GM",
	  "Asks to set the unit to the basic GM state.",
	  NULL, P(SC88),
	  { B(SELECT) }, 1, B(PART_RIGHT), false, "manual p.4-18", COMBO_HOLD_THEN_PRESS },
	{ "Initialize for GS",
	  "Asks to set the unit to the basic GS state.",
	  NULL, P(SC88),
	  { B(SELECT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.4-18", COMBO_HOLD_THEN_PRESS },
	{ "Select CM-64 sounds",
	  "Asks to switch the unit to the CM-64 sound map, losing every previous setting.",
	  NULL, P(SC88),
	  { B(SELECT) }, 1, B(INSTRUMENT_LEFT), false, "manual p.4-14", COMBO_HOLD_THEN_PRESS },
	{ "Draw pictures or characters on the screen (Frame Draw)",
	  "Enters and leaves Frame Draw, where the display's dots are drawn by hand over ten pages.",
	  NULL, P(SC88),
	  { B(EDIT1_RIGHT) }, 1, B(EDIT2_LEFT), false, "manual p.4-12", COMBO_TOGETHER },
	{ "transmit screen data to external device",
	  "Sends the current Frame Draw page as exclusive data.",
	  "Frame Draw", P(SC88),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.4-12", COMBO_TOGETHER },

	/* Service notes -- "TEST MODE / Switch operations" and "IDENTIFYING VERSION NUMBER"
	 * (Roland SC-88 Service Notes, First Edition, Jun.1994, p.4 and p.9).  The direct-select
	 * list is for Program ROM version 1.02 and later; entry and tests 1 and 3 are common to
	 * version 1.01 as well.  The rear Select SW is not a panel button and cannot be set here. */
#if COMBOS_TEST_MODE
	{ "Normal Test Mode",
	  "Rear Select SW on MIDI: held while switching on, enters the factory Test Mode.",
	  "power-on", P(SC88),
	  { B(KEY_SHIFT_LEFT), B(KEY_SHIFT_RIGHT) }, 2, NONE, true, "service notes p.4", COMBO_TOGETHER },
	{ "Serial Test (4')",
	  "The same hold with the rear Select SW on Mac enters the Test Mode at the Serial Test instead.",
	  "power-on", P(SC88),
	  { B(KEY_SHIFT_LEFT), B(KEY_SHIFT_RIGHT) }, 2, NONE, true, "service notes p.4", COMBO_TOGETHER },
#endif
	{ "THRU Check",
	  "Rear Select SW on MIDI: held while switching on, puts the unit in the MIDI THRU check.",
	  "power-on", P(SC88),
	  { B(REVERB_LEFT), B(CHORUS_RIGHT) }, 2, NONE, true, "service notes p.4", COMBO_TOGETHER },
	{ "Identifying version number",
	  "Held while switching on, shows the ROM, sub-CPU, XPGS-core and parameter versions.",
	  "power-on", P(SC88),
	  { B(MIDI_CH_LEFT), B(MIDI_CH_RIGHT) }, 2, NONE, true, "service notes p.9", COMBO_TOGETHER },
#if COMBOS_TEST_MODE
	{ "To move to the next test.",
	  "In Test Mode, steps to the following test.",
	  "Test Mode", P(SC88),
	  { B(KEY_SHIFT_LEFT) }, 1, B(MIDI_CH_RIGHT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "To return to the preceding test.",
	  "In Test Mode, steps back to the previous test.",
	  "Test Mode", P(SC88),
	  { B(KEY_SHIFT_LEFT) }, 1, B(MIDI_CH_LEFT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "To perform the same test once again.",
	  "In Test Mode, restarts the test that is running.",
	  "Test Mode", P(SC88),
	  { B(KEY_SHIFT_LEFT) }, 1, B(PAN_RIGHT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "1. LCD & LED Test",
	  "In Test Mode, jumps to the LCD and LED test.",
	  "Test Mode", P(SC88),
	  { B(KEY_SHIFT_LEFT) }, 1, B(PART_LEFT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "2. Memory Test",
	  "In Test Mode, jumps to the memory test: SRAM, DRAM, the wave ROMs, the XP chip and the PROM.",
	  "Test Mode", P(SC88),
	  { B(KEY_SHIFT_LEFT) }, 1, B(PART_RIGHT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "3. Switch Test",
	  "In Test Mode, jumps to the switch test, which names each panel switch as it is pressed.",
	  "Test Mode", P(SC88),
	  { B(KEY_SHIFT_LEFT) }, 1, B(INSTRUMENT_LEFT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "4. MIDI & Battery Test",
	  "In Test Mode, jumps to the MIDI loop and battery-voltage test.",
	  "Test Mode", P(SC88),
	  { B(KEY_SHIFT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "5. Sound & Effect Test",
	  "In Test Mode, jumps to the sound and effect test, which walks the two outputs.",
	  "Test Mode", P(SC88),
	  { B(KEY_SHIFT_LEFT) }, 1, B(LEVEL_LEFT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
#endif

	/* ================================================================ SC-88VL
	 * Owner's manual "SC-88VL_e2", pages numbered straight through; "Parameter list and
	 * operations" is p.56-59.  The VL has neither the lower face nor a Preview switch, so the
	 * delay level lives under [EQ] and the module and initialize operations are held through
	 * the power-on instead of under [SELECT]. */
	{ "the value will change faster",
	  "Holding one half of the Part pair and pressing the other steps the Part number quickly.",
	  NULL, P(SC88VL),
	  { B(PART_LEFT) }, 1, B(PART_RIGHT), false, "manual p.6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Instrument pair and pressing the other steps the sound quickly.",
	  NULL, P(SC88VL),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Level pair and pressing the other changes the level quickly.",
	  NULL, P(SC88VL),
	  { B(LEVEL_LEFT) }, 1, B(LEVEL_RIGHT), false, "manual p.6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Pan pair and pressing the other changes the pan quickly.",
	  NULL, P(SC88VL),
	  { B(PAN_LEFT) }, 1, B(PAN_RIGHT), false, "manual p.6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Reverb pair and pressing the other changes the reverb level quickly.",
	  NULL, P(SC88VL),
	  { B(REVERB_LEFT) }, 1, B(REVERB_RIGHT), false, "manual p.6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Chorus pair and pressing the other changes the chorus level quickly.",
	  NULL, P(SC88VL),
	  { B(CHORUS_LEFT) }, 1, B(CHORUS_RIGHT), false, "manual p.6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the Key Shift pair and pressing the other transposes quickly.",
	  NULL, P(SC88VL),
	  { B(KEY_SHIFT_LEFT) }, 1, B(KEY_SHIFT_RIGHT), false, "manual p.6", COMBO_HOLD_THEN_PRESS },
	{ "the value will change faster",
	  "Holding one half of the MIDI Channel pair and pressing the other steps the channel quickly.",
	  NULL, P(SC88VL),
	  { B(MIDI_CH_LEFT) }, 1, B(MIDI_CH_RIGHT), false, "manual p.6", COMBO_HOLD_THEN_PRESS },

	{ "To switch between the A and B Parts",
	  "Flips the Part display between Parts A01-A16 and Parts B01-B16.",
	  "Part display", P(SC88VL),
	  { B(ALL) }, 1, B(PART_LEFT), false, "manual p.12", COMBO_TOGETHER },
	{ "Select a Variation sound",
	  "Enters and leaves Variation select, where the Instrument buttons pick the Variation number.",
	  "Part display", P(SC88VL),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.12", COMBO_TOGETHER },
	{ "To switch between the A and B",
	  "Flips the Part's MIDI channel display between group A and group B channels.",
	  "Part display", P(SC88VL),
	  { B(KEY_SHIFT_RIGHT) }, 1, B(MIDI_CH_LEFT), false, "manual p.14", COMBO_TOGETHER },
	{ "PART Monitor",
	  "Listens to the selected Part alone.",
	  "Part display", P(SC88VL),
	  { B(ALL) }, 1, B(MUTE), false, "manual p.16", COMBO_TOGETHER },
	{ "Individual Part settings",
	  "Opens and closes the per-Part parameter menu, from Part Mode to the Channel Aftertouch block.",
	  "Part display (ALL dark)", P(SC88VL),
	  { B(PART_LEFT) }, 1, B(PART_RIGHT), false, "manual p.16", COMBO_TOGETHER },
	{ "Overall Part settings",
	  "Opens and closes the all-Parts menu: Master Tune, the system effects and the receive switches.",
	  "All display (ALL lit)", P(SC88VL),
	  { B(PART_LEFT) }, 1, B(PART_RIGHT), false, "manual p.10", COMBO_TOGETHER },
	{ "graphically display the current setting",
	  "Draws the Level of every Part as bars; the same press returns to the normal display.",
	  "Part or All display", P(SC88VL),
	  { B(LEVEL_LEFT) }, 1, B(LEVEL_RIGHT), false, "manual p.22", COMBO_TOGETHER },
	{ "graphically display the current setting",
	  "Draws Pan graphically; the same press returns to the normal display.",
	  "Part or All display", P(SC88VL),
	  { B(PAN_LEFT) }, 1, B(PAN_RIGHT), false, "manual p.22", COMBO_TOGETHER },
	{ "graphically display the current setting",
	  "Draws Key Shift graphically; the same press returns to the normal display.",
	  "Part or All display", P(SC88VL),
	  { B(KEY_SHIFT_LEFT) }, 1, B(KEY_SHIFT_RIGHT), false, "manual p.22", COMBO_TOGETHER },
	{ "the current parameter values ... displayed graphically",
	  "Draws the reverb send level graphically; the same press returns to the normal display.",
	  "Part or All display", P(SC88VL),
	  { B(REVERB_LEFT) }, 1, B(REVERB_RIGHT), false, "manual p.25", COMBO_TOGETHER },
	{ "the current parameter values ... displayed graphically",
	  "Draws the chorus send level graphically; the same press returns to the normal display.",
	  "Part or All display", P(SC88VL),
	  { B(CHORUS_LEFT) }, 1, B(CHORUS_RIGHT), false, "manual p.25", COMBO_TOGETHER },
	{ "While holding button [EQ], press button KEY SHIFT [l]",
	  "Lowers the delay send level of the Part, or of all Parts when the ALL indicator is lit.",
	  "Part or All display", P(SC88VL),
	  { B(SC88_MAP) }, 1, B(KEY_SHIFT_LEFT), false, "manual p.25", COMBO_HOLD_THEN_PRESS },
	{ "While holding button [EQ], press button KEY SHIFT [r]",
	  "Raises the delay send level of the Part, or of all Parts when the ALL indicator is lit.",
	  "Part or All display", P(SC88VL),
	  { B(SC88_MAP) }, 1, B(KEY_SHIFT_RIGHT), false, "manual p.25", COMBO_HOLD_THEN_PRESS },
	{ "System functions",
	  "Opens and closes the System-parameter menu, from Display Type to the Backup switch.",
	  NULL, P(SC88VL),
	  { B(SC55_MAP) }, 1, B(SC88_MAP), false, "manual p.24", COMBO_TOGETHER },
	{ "Set a display name",
	  "Enters and leaves editing of the name the display shows, character by character.",
	  "All display (ALL lit)", P(SC88VL),
	  { B(PAN_RIGHT) }, 1, B(CHORUS_RIGHT), false, "manual p.34", COMBO_TOGETHER },
	{ "Bulk dump",
	  "Asks which block of memory to transmit as System Exclusive data.",
	  "All display (ALL lit)", P(SC88VL),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.30", COMBO_TOGETHER },
	{ "Single Module mode",
	  "Held while switching on, asks to return to one 32-Part module.",
	  "power-on", P(SC88VL),
	  { B(KEY_SHIFT_LEFT) }, 1, NONE, true, "manual p.32", COMBO_TOGETHER },
	{ "Double Module mode",
	  "Held while switching on, asks to split the unit into two GM/GS modules with their own system effects.",
	  "power-on", P(SC88VL),
	  { B(KEY_SHIFT_RIGHT) }, 1, NONE, true, "manual p.32", COMBO_TOGETHER },
	{ "Reset to factory settings",
	  "Held while switching on, asks to restore every setting, System and User parameters included.",
	  "power-on", P(SC88VL),
	  { B(INSTRUMENT_LEFT), B(INSTRUMENT_RIGHT) }, 2, NONE, true, "manual p.33", COMBO_TOGETHER },
	{ "Initialize for General MIDI",
	  "Held while switching on, asks to set the unit to the basic GM state.",
	  "power-on", P(SC88VL),
	  { B(PART_RIGHT) }, 1, NONE, true, "manual p.33", COMBO_TOGETHER },
	{ "Initialize for GS",
	  "Held while switching on, asks to set the unit to the basic GS state.",
	  "power-on", P(SC88VL),
	  { B(INSTRUMENT_RIGHT) }, 1, NONE, true, "manual p.33", COMBO_TOGETHER },
	{ "Select CM-64 sounds",
	  "Held while switching on, asks to switch the unit to the CM-64 sound map.",
	  "power-on", P(SC88VL),
	  { B(INSTRUMENT_LEFT) }, 1, NONE, true, "manual p.31", COMBO_TOGETHER },

	/* Service notes -- "TEST MODE / Switch operations" and "IDENTIFYING VERSION NUMBER"
	 * (Roland SC-88VL Service Notes, p.4 and p.8, with the errata sheets ER00197 and ER00198 of
	 * 1997-01-08).  The VL is put in standby first and its POWER key must follow the chord
	 * quickly; the host's power switch stands in for that here. */
#if COMBOS_TEST_MODE
	{ "Normal Test Mode",
	  "From standby with the rear Select SW on MIDI, the four keys held as the power comes on enter the Test Mode.",
	  "power-on", P(SC88VL),
	  { B(INSTRUMENT_LEFT), B(INSTRUMENT_RIGHT), B(KEY_SHIFT_LEFT), B(KEY_SHIFT_RIGHT) }, 4, NONE, true,
	  "service notes p.4", COMBO_TOGETHER },
	{ "Serial Test (4')",
	  "The same chord with the rear Select SW on Mac enters the Test Mode at the Serial Test instead.",
	  "power-on", P(SC88VL),
	  { B(INSTRUMENT_LEFT), B(INSTRUMENT_RIGHT), B(KEY_SHIFT_LEFT), B(KEY_SHIFT_RIGHT) }, 4, NONE, true,
	  "service notes p.4", COMBO_TOGETHER },
	{ "To exit the Test Mode",
	  "The same chord leaves the Test Mode, with no power cycle.",
	  "Test Mode", P(SC88VL),
	  { B(INSTRUMENT_LEFT), B(INSTRUMENT_RIGHT), B(KEY_SHIFT_LEFT) }, 3, B(KEY_SHIFT_RIGHT), false,
	  "service notes p.4", COMBO_HOLD_THEN_PAIR },
#endif
	{ "THRU Check",
	  "Rear Select SW on MIDI: held while switching on, puts the unit in the MIDI THRU check.",
	  "power-on", P(SC88VL),
	  { B(REVERB_LEFT), B(CHORUS_RIGHT) }, 2, NONE, true, "service notes p.4", COMBO_TOGETHER },
	{ "Identifying version number",
	  "Held as the power comes on, shows the ROM, sub-CPU, XPGS-core and parameter versions.",
	  "power-on", P(SC88VL),
	  { B(INSTRUMENT_LEFT), B(INSTRUMENT_RIGHT), B(MIDI_CH_LEFT), B(MIDI_CH_RIGHT) }, 4, NONE, true,
	  "service notes p.8 (errata ER00198)", COMBO_TOGETHER },
#if COMBOS_TEST_MODE
	{ "To move to the next test.",
	  "In Test Mode, steps to the following test.",
	  "Test Mode", P(SC88VL),
	  { B(KEY_SHIFT_LEFT) }, 1, B(MIDI_CH_RIGHT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "To return to the preceding test.",
	  "In Test Mode, steps back to the previous test.",
	  "Test Mode", P(SC88VL),
	  { B(KEY_SHIFT_LEFT) }, 1, B(MIDI_CH_LEFT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "To perform the same test once again.",
	  "In Test Mode, restarts the test that is running.",
	  "Test Mode", P(SC88VL),
	  { B(KEY_SHIFT_LEFT) }, 1, B(PAN_RIGHT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "1. LCD & LED Test",
	  "In Test Mode, jumps to the LCD and LED test.",
	  "Test Mode", P(SC88VL),
	  { B(KEY_SHIFT_LEFT) }, 1, B(PART_LEFT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "2. Memory Test",
	  "In Test Mode, jumps to the memory test: SRAM, DRAM, the wave ROMs, the XP chip and the PROM.",
	  "Test Mode", P(SC88VL),
	  { B(KEY_SHIFT_LEFT) }, 1, B(PART_RIGHT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "3. Switch Test",
	  "In Test Mode, jumps to the switch test, which names each panel switch as it is pressed.",
	  "Test Mode", P(SC88VL),
	  { B(KEY_SHIFT_LEFT) }, 1, B(INSTRUMENT_LEFT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "4. MIDI & Battery Test",
	  "In Test Mode, jumps to the MIDI loop and battery-voltage test.",
	  "Test Mode", P(SC88VL),
	  { B(KEY_SHIFT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "5. Sound & Effect Test",
	  "In Test Mode, jumps to the sound and effect test, which walks the two outputs.",
	  "Test Mode", P(SC88VL),
	  { B(KEY_SHIFT_LEFT) }, 1, B(LEVEL_LEFT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "6. Fact Data Load",
	  "In Test Mode, loads the factory setup back into memory; the notes give no procedure for it.",
	  "Test Mode", P(SC88VL),
	  { B(KEY_SHIFT_LEFT) }, 1, B(LEVEL_RIGHT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
#endif

	/* ================================================================ SC-55mkII
	 * Owner's manual "SC-55mkII_e"; its "TABLE OF OPERATIONS" (p.108-109) and "OPERATION BLOCK
	 * DIAGRAM" (p.110-111) are the spine, and page numbers below are the body pages they point
	 * at.  The panel has neither map keys nor a lower face, so what the SC-88 does with
	 * [SELECT] this machine does with a key held through the power-on. */
	{ "Part Monitor",
	  "Listens to the selected Part alone.",
	  "Part display", P(SC55MK2),
	  { B(ALL) }, 1, B(MUTE), false, "manual p.32", COMBO_TOGETHER },
	{ "Settings for each part",
	  "Opens and closes the per-Part parameter menu, from Part Mode to Portamento Time; [ALL] and [MUTE] step through it.",
	  "Part display (ALL dark)", P(SC55MK2),
	  { B(PART_LEFT) }, 1, B(PART_RIGHT), false, "manual p.51", COMBO_TOGETHER },
	{ "Settings for all parts",
	  "Opens and closes the all-Parts menu, from Master Tune to Use Universal Realtime Ex.",
	  "All display (ALL lit)", P(SC55MK2),
	  { B(PART_LEFT) }, 1, B(PART_RIGHT), false, "manual p.33", COMBO_TOGETHER },
	{ "Indicator on / Indicator off",
	  "Inside the menu, switches between the all-Parts parameters and the selected Part's.",
	  "parameter menu", P(SC55MK2),
	  { B(ALL) }, 1, B(PART_LEFT), false, "manual p.111", COMBO_TOGETHER },
	{ "Selection of Variation",
	  "Enters and leaves Variation select, where the Instrument buttons pick the Variation.",
	  "Part display", P(SC55MK2),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.45", COMBO_TOGETHER },
	{ "USER ON, USER OFF",
	  "Turns the User settings on and off; with them off the unit plays the preset sounds.",
	  NULL, P(SC55MK2),
	  { B(LEVEL_RIGHT) }, 1, B(REVERB_RIGHT), false, "manual p.28", COMBO_TOGETHER },
	{ "Clear the setting",
	  "Asks to clear the User settings; [ALL] executes and [MUTE] cancels.",
	  NULL, P(SC55MK2),
	  { B(PAN_LEFT) }, 1, B(CHORUS_LEFT), false, "manual p.29", COMBO_TOGETHER },
	{ "Minus-one Play",
	  "Mutes the Part on the selected MIDI channel so it can be played live.",
	  "Part display", P(SC55MK2),
	  { B(LEVEL_LEFT) }, 1, B(REVERB_LEFT), false, "manual p.34", COMBO_TOGETHER },
	{ "Changing the Patch name",
	  "Enters and leaves Patch-name editing: Part moves the cursor, Instrument picks the character.",
	  "All display (ALL lit)", P(SC55MK2),
	  { B(PAN_RIGHT) }, 1, B(CHORUS_RIGHT), false, "manual p.40", COMBO_TOGETHER },
	{ "Store",
	  "Asks to store the whole state of the unit into the User area; [ALL] executes.",
	  "All display (ALL lit)", P(SC55MK2),
	  { B(PART_LEFT) }, 1, B(INSTRUMENT_LEFT), false, "manual p.41", COMBO_TOGETHER },
	{ "Call",
	  "Asks to load the stored state back out of the User area; [ALL] executes.",
	  "All display (ALL lit)", P(SC55MK2),
	  { B(PART_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.41", COMBO_TOGETHER },
	{ "GS Setup Send",
	  "Transmits the basic settings of every Part as GS exclusive data; [ALL] executes.",
	  "All display (ALL lit)", P(SC55MK2),
	  { B(PART_RIGHT) }, 1, B(INSTRUMENT_LEFT), false, "manual p.59", COMBO_TOGETHER },
	{ "GM Setup Send",
	  "Transmits the basic settings of every Part as GM messages; [ALL] executes.",
	  "All display (ALL lit)", P(SC55MK2),
	  { B(KEY_SHIFT_RIGHT) }, 1, B(MIDI_CH_LEFT), false, "manual p.59", COMBO_TOGETHER },
	{ "DUMP All",
	  "Asks to transmit every setting of the unit as System Exclusive data; [ALL] executes.",
	  "All display (ALL lit)", P(SC55MK2),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.60", COMBO_TOGETHER },
	{ "DUMP ALL+",
	  "Inside the all-Parts menu, asks to transmit every setting and the Parts not muted.",
	  "all-Parts parameter menu", P(SC55MK2),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.61", COMBO_TOGETHER },
	{ "DUMP PART",
	  "Inside the Part menu, asks to transmit the settings of the selected Part.",
	  "Part parameter menu", P(SC55MK2),
	  { B(INSTRUMENT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "manual p.62", COMBO_TOGETHER },
	{ "Set to ROM play status",
	  "Held while switching on, puts the unit in ROM play: Part selects the song, [ALL] starts it and [MUTE] stops it.",
	  "power-on", P(SC55MK2),
	  { B(PART_LEFT), B(PART_RIGHT) }, 2, NONE, true, "manual p.17", COMBO_TOGETHER },
	{ "Cancel ROM play status",
	  "Leaves ROM play and returns to the Part display.",
	  "ROM play", P(SC55MK2),
	  { B(PART_LEFT) }, 1, B(PART_RIGHT), false, "manual p.17", COMBO_TOGETHER },
	{ "Sound arrangement of MT-32",
	  "Held while switching on, asks to set the unit up to play MT-32 song data; [ALL] executes.",
	  "power-on", P(SC55MK2),
	  { B(INSTRUMENT_LEFT) }, 1, NONE, true, "manual p.38", COMBO_TOGETHER },
	{ "Initialization for GM system",
	  "Held while switching on, asks to set the unit to the basic GM state; [ALL] executes.",
	  "power-on", P(SC55MK2),
	  { B(PART_LEFT) }, 1, NONE, true, "manual p.36", COMBO_TOGETHER },
	{ "Initialization for GS format",
	  "Held while switching on, asks to set the unit to the basic GS state; [ALL] executes.",
	  "power-on", P(SC55MK2),
	  { B(INSTRUMENT_RIGHT) }, 1, NONE, true, "manual p.36", COMBO_TOGETHER },
	{ "Returning to factory presets",
	  "Held while switching on, asks \"Init All, Sure?\" to restore every setting; [ALL] executes.",
	  "power-on", P(SC55MK2),
	  { B(INSTRUMENT_LEFT), B(INSTRUMENT_RIGHT) }, 2, NONE, true, "manual p.37", COMBO_TOGETHER },

	/* Service notes -- "TEST MODE / Switch operations" and "IDENTIFYING VERSION NUMBER"
	 * (Roland SC-55mkII Service Notes, p.4 and p.8).  Both are entered from standby: the
	 * STANDBY key is a position in the machine's own matrix, so it keeps scanning the panel
	 * with the unit apparently off. */
#if COMBOS_TEST_MODE
	{ "To enter the Test Mode",
	  "From standby, enters the factory Test Mode at T-1.",
	  "standby", P(SC55MK2),
	  { B(INSTRUMENT_LEFT), B(INSTRUMENT_RIGHT), B(KEY_SHIFT_LEFT) }, 3, B(KEY_SHIFT_RIGHT), false,
	  "service notes p.4", COMBO_HOLD_THEN_PAIR },
	{ "To exit the Test Mode",
	  "Leaves the Test Mode.",
	  "Test Mode", P(SC55MK2),
	  { B(INSTRUMENT_LEFT), B(INSTRUMENT_RIGHT), B(KEY_SHIFT_LEFT) }, 3, B(KEY_SHIFT_RIGHT), false,
	  "service notes p.4", COMBO_HOLD_THEN_PAIR },
#endif
	{ "Identifying version number",
	  "From standby, shows the version numbers of the CPU, the sub CPU and the 4M ROM, and the version date.",
	  "standby", P(SC55MK2),
	  { B(INSTRUMENT_LEFT), B(INSTRUMENT_RIGHT), B(MIDI_CH_LEFT) }, 3, B(MIDI_CH_RIGHT), false,
	  "service notes p.8", COMBO_HOLD_THEN_PAIR },
#if COMBOS_TEST_MODE
	{ "To move to the next test.",
	  "In Test Mode, steps to the following test.",
	  "Test Mode", P(SC55MK2),
	  { B(KEY_SHIFT_LEFT) }, 1, B(MIDI_CH_RIGHT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "To return to the preceding test.",
	  "In Test Mode, steps back to the previous test.",
	  "Test Mode", P(SC55MK2),
	  { B(KEY_SHIFT_LEFT) }, 1, B(MIDI_CH_LEFT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "To perform the same test once again",
	  "In Test Mode, restarts the test that is running.",
	  "Test Mode", P(SC55MK2),
	  { B(KEY_SHIFT_LEFT) }, 1, B(PAN_RIGHT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "1. LCD & LED Test",
	  "In Test Mode, jumps to the LCD and LED test.",
	  "Test Mode", P(SC55MK2),
	  { B(KEY_SHIFT_LEFT) }, 1, B(PART_LEFT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "2. Memory Test",
	  "In Test Mode, jumps to the memory test.",
	  "Test Mode", P(SC55MK2),
	  { B(KEY_SHIFT_LEFT) }, 1, B(PART_RIGHT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "3. Switch Test & Remote Control Test",
	  "In Test Mode, jumps to the switch and remote-control test.",
	  "Test Mode", P(SC55MK2),
	  { B(KEY_SHIFT_LEFT) }, 1, B(INSTRUMENT_LEFT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "4. MIDI & Battery Test",
	  "In Test Mode, jumps to the MIDI loop and battery-voltage test.",
	  "Test Mode", P(SC55MK2),
	  { B(KEY_SHIFT_LEFT) }, 1, B(INSTRUMENT_RIGHT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "5. Sound Test",
	  "In Test Mode, jumps to the sound test.",
	  "Test Mode", P(SC55MK2),
	  { B(KEY_SHIFT_LEFT) }, 1, B(LEVEL_LEFT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "6. Effect Test",
	  "In Test Mode, jumps to the effect test.",
	  "Test Mode", P(SC55MK2),
	  { B(KEY_SHIFT_LEFT) }, 1, B(LEVEL_RIGHT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
	{ "7. Factory Data Load",
	  "In Test Mode, loads the factory setup back into memory.",
	  "Test Mode", P(SC55MK2),
	  { B(KEY_SHIFT_LEFT) }, 1, B(PAN_LEFT), false, "service notes p.4", COMBO_HOLD_THEN_PRESS },
#endif

	/* ================================================================ SC-8850
	 * Owner's manual "SC-8850_e3"; "Operating Procedure List" (p.158-166) is the spine, and
	 * "Operations while holding the [SHIFT] button" (p.166) is the whole of the [SHIFT] set.
	 * The panel prints the two brackets those combinations make: UTIL over [EDIT] and PART [l],
	 * ALL over PART [l] and [r]. */
	{ "the value will change faster",
	  "Holding one of the value keys and pressing the other steps the value quickly.",
	  NULL, P(SC8850),
	  { B(DEC) }, 1, B(INC), false, "manual p.30", COMBO_HOLD_THEN_PRESS },
	{ "All Part screen",
	  "Opens the All Part screen, where the whole unit is muted or its map forced at once.",
	  "Part Basic screen", P(SC8850),
	  { B(PART_LEFT) }, 1, B(PART_RIGHT), false, "manual p.158", COMBO_TOGETHER },
	{ "Edit All screen",
	  "From the Edit screen, opens the Edit All screen: master level, pan, key shift, tune and device ID.",
	  "Edit screen", P(SC8850),
	  { B(PART_LEFT) }, 1, B(PART_RIGHT), false, "manual p.158", COMBO_TOGETHER },
	{ "Utility screen",
	  "Opens the Utility screen: the system parameters, bulk dump, initialize and the demo songs.",
	  NULL, P(SC8850),
	  { B(EDIT) }, 1, B(PART_LEFT), false, "manual p.158", COMBO_TOGETHER },
	{ "Transmits the value of the selected parameter",
	  "Sends the parameter under the cursor as exclusive data.",
	  "Edit, Edit All, Drum or Effect screen", P(SC8850),
	  { B(DEC) }, 1, B(INC), false, "manual p.161", COMBO_TOGETHER },
	{ "Initializes All (Factory Preset)",
	  "Asks \"Initialize Sure?\" to restore every setting, the System and User parameters included.",
	  NULL, P(SC8850),
	  { B(SHIFT) }, 1, B(PART_LEFT), false, "manual p.23", COMBO_HOLD_THEN_PRESS },
	{ "Initializes GS (GS Reset)",
	  "Asks to set the unit to the basic GS state.",
	  NULL, P(SC8850),
	  { B(SHIFT) }, 1, B(PART_RIGHT), false, "manual p.24", COMBO_HOLD_THEN_PRESS },
	{ "Initializes GM1 (GM1 System On)",
	  "Asks to set the unit to the basic GM1 state.",
	  NULL, P(SC8850),
	  { B(SHIFT) }, 1, B(DOWN), false, "manual p.25", COMBO_HOLD_THEN_PRESS },
	{ "Initializes GM2 (GM2 System On)",
	  "Asks to set the unit to the basic GM2 state.",
	  NULL, P(SC8850),
	  { B(SHIFT) }, 1, B(UP), false, "manual p.26", COMBO_HOLD_THEN_PRESS },
	{ "Enters the DEMO screen",
	  "Opens the demo-song screen, where [ENTER] plays the chosen song.",
	  NULL, P(SC8850),
	  { B(SHIFT) }, 1, B(EDIT), false, "manual p.27", COMBO_HOLD_THEN_PRESS },
	{ "Enters the Load User Setting screen",
	  "Loads the settings stored in the user area back into the unit.",
	  NULL, P(SC8850),
	  { B(SHIFT) }, 1, B(DRUM), false, "manual p.138", COMBO_HOLD_THEN_PRESS },
	{ "Turns PART EFX On/Off",
	  "Switches the insertion effect of the selected Part on and off.",
	  NULL, P(SC8850),
	  { B(SHIFT) }, 1, B(EFFECTS), false, "manual p.89", COMBO_HOLD_THEN_PRESS },

	/* Service notes -- "TEST MODE" and "UPGRADING PROCEDURE" (Roland SC-8850 Service Notes,
	 * Jun.1999, p.6-10).  The rear selector must be at MIDI for the test mode, and the two
	 * upgrade chords erase a flash memory that then has to be reloaded from SMF. */
#if COMBOS_TEST_MODE
	{ "Entering the test mode",
	  "Rear selector on MIDI: held while switching on, enters the factory Test Mode at its menu.",
	  "power-on", P(SC8850),
	  { B(F3), B(PART_LEFT), B(INC) }, 3, NONE, true, "service notes p.8", COMBO_TOGETHER },
#endif
	{ "Verifying version number",
	  "The same hold shows the program version; [F2] then shows the CPU version and [F3] the tone parameters.",
	  "power-on", P(SC8850),
	  { B(F3), B(PART_LEFT), B(INC) }, 3, NONE, true, "service notes p.8", COMBO_TOGETHER },
#if COMBOS_TEST_MODE
	{ "Return back to the test mode menu screen",
	  "In Test Mode, leaves the running test and returns to the menu.",
	  "Test Mode", P(SC8850),
	  { B(SHIFT) }, 1, B(MUTE), false, "service notes p.8", COMBO_HOLD_THEN_PRESS },
	{ "Test 1 Version",
	  "In Test Mode, jumps to the version screen.",
	  "Test Mode", P(SC8850),
	  { B(SHIFT) }, 1, B(EDIT), false, "service notes p.8", COMBO_HOLD_THEN_PRESS },
	{ "Test 2 Device test",
	  "In Test Mode, jumps to the device test, which walks the chips in turn.",
	  "Test Mode", P(SC8850),
	  { B(SHIFT) }, 1, B(PART_LEFT), false, "service notes p.8", COMBO_HOLD_THEN_PRESS },
	{ "Test 3 Switch/LED test",
	  "In Test Mode, jumps to the switch and LED test, which names each key as it is pressed.",
	  "Test Mode", P(SC8850),
	  { B(SHIFT) }, 1, B(PART_RIGHT), false, "service notes p.8", COMBO_HOLD_THEN_PRESS },
	{ "Test 4 LCD & Encoder test",
	  "In Test Mode, jumps to the display and value-dial test.",
	  "Test Mode", P(SC8850),
	  { B(SHIFT) }, 1, B(DRUM), false, "service notes p.8", COMBO_HOLD_THEN_PRESS },
	{ "Test 5 MIDI test",
	  "In Test Mode, jumps to the MIDI loop test.",
	  "Test Mode", P(SC8850),
	  { B(SHIFT) }, 1, B(DOWN), false, "service notes p.8", COMBO_HOLD_THEN_PRESS },
	{ "Test 6 Serial test",
	  "In Test Mode, jumps to the serial test, which needs the COMPUTER test cable.",
	  "Test Mode", P(SC8850),
	  { B(SHIFT) }, 1, B(UP), false, "service notes p.8", COMBO_HOLD_THEN_PRESS },
	{ "Test 7 Sound test",
	  "In Test Mode, jumps to the sound test.",
	  "Test Mode", P(SC8850),
	  { B(SHIFT) }, 1, B(EFFECTS), false, "service notes p.8", COMBO_HOLD_THEN_PRESS },
	{ "Test 8 EFFECTS test",
	  "In Test Mode, jumps to the effects test.",
	  "Test Mode", P(SC8850),
	  { B(SHIFT) }, 1, B(EXIT), false, "service notes p.8", COMBO_HOLD_THEN_PRESS },
	{ "Test 9 Factory preset data load",
	  "In Test Mode, loads the factory preset data back into memory.",
	  "Test Mode", P(SC8850),
	  { B(SHIFT) }, 1, B(ENTER), false, "service notes p.8", COMBO_HOLD_THEN_PRESS },
#endif
	{ "Updating the program",
	  "Held while switching on, erases the 8M program flash and waits for the update SMFs.",
	  "power-on", P(SC8850),
	  { B(MUTE), B(EXIT), B(EDIT), B(F2) }, 4, NONE, true, "service notes p.6", COMBO_TOGETHER },
	{ "Updating the tone parameters",
	  "Held while switching on, erases the 16M tone-parameter flash and waits for the update SMFs.",
	  "power-on", P(SC8850),
	  { B(MUTE), B(EXIT), B(EDIT), B(F3) }, 4, NONE, true, "service notes p.7", COMBO_TOGETHER },
};

const int combo_count = (int)(sizeof combos / sizeof combos[0]);

int combos_for(panel_model_t panel, scemu_button_t button, int *out, int max)
{
	int n = 0;

	for (int i = 0; i < combo_count; i++)
	{
		if (combos[i].panel != panel)
			continue;

		bool involved = combos[i].press == button;

		for (int j = 0; !involved && j < combos[i].hold_count; j++)
			if (combos[i].hold[j] == button)
				involved = true;
		if (!involved)
			continue;
		if (n < max && out)
			out[n] = i;
		n++;
	}
	return n > max ? max : n;
}

/* Every key in the words of the panel it is on: the shared reading first, then what a model
 * prints in its place.  A key a panel does not carry has no name there. */
static const char *const label_common[SCEMU_BUTTON_COUNT] = {
	[SCEMU_BUTTON_ALL] = "ALL", [SCEMU_BUTTON_MUTE] = "MUTE",
	[SCEMU_BUTTON_SC55_MAP] = "SC-55 MAP", [SCEMU_BUTTON_SC88_MAP] = "SC-88 MAP",
	[SCEMU_BUTTON_PREVIEW] = "PREVIEW (push the knob)",
	[SCEMU_BUTTON_PART_LEFT] = "PART ◀", [SCEMU_BUTTON_PART_RIGHT] = "PART ▶",
	[SCEMU_BUTTON_INSTRUMENT_LEFT] = "INSTRUMENT ◀", [SCEMU_BUTTON_INSTRUMENT_RIGHT] = "INSTRUMENT ▶",
	[SCEMU_BUTTON_LEVEL_LEFT] = "LEVEL ◀", [SCEMU_BUTTON_LEVEL_RIGHT] = "LEVEL ▶",
	[SCEMU_BUTTON_PAN_LEFT] = "PAN ◀", [SCEMU_BUTTON_PAN_RIGHT] = "PAN ▶",
	[SCEMU_BUTTON_REVERB_LEFT] = "REVERB ◀", [SCEMU_BUTTON_REVERB_RIGHT] = "REVERB ▶",
	[SCEMU_BUTTON_CHORUS_LEFT] = "CHORUS ◀", [SCEMU_BUTTON_CHORUS_RIGHT] = "CHORUS ▶",
	[SCEMU_BUTTON_KEY_SHIFT_LEFT] = "KEY SHIFT/DELAY ◀", [SCEMU_BUTTON_KEY_SHIFT_RIGHT] = "KEY SHIFT/DELAY ▶",
	[SCEMU_BUTTON_MIDI_CH_LEFT] = "MIDI CH ◀", [SCEMU_BUTTON_MIDI_CH_RIGHT] = "MIDI CH ▶",
	[SCEMU_BUTTON_USER_INST] = "USER INST/EFX", [SCEMU_BUTTON_SELECT] = "SELECT/EFX ON/OFF",
	[SCEMU_BUTTON_EDIT1_LEFT] = "VIB RATE·ATTACK·EFX TYPE ◀", [SCEMU_BUTTON_EDIT1_RIGHT] = "VIB RATE·ATTACK·EFX TYPE ▶",
	[SCEMU_BUTTON_EDIT2_LEFT] = "VIB DEPTH·CUTOFF·DECAY·EFX PARAM ◀", [SCEMU_BUTTON_EDIT2_RIGHT] = "VIB DEPTH·CUTOFF·DECAY·EFX PARAM ▶",
	[SCEMU_BUTTON_EDIT3_LEFT] = "VIB DELAY·RESONANCE·RELEASE·EFX VALUE ◀", [SCEMU_BUTTON_EDIT3_RIGHT] = "VIB DELAY·RESONANCE·RELEASE·EFX VALUE ▶",
};

/* the SC-88's fourth strip key is EQ, and its three edit pairs are printed DELAY, INSTRUMENT
   and VARIATION under the parameter names */
static const char *const label_sc88[SCEMU_BUTTON_COUNT] = {
	[SCEMU_BUTTON_SC55_MAP] = "SC-55 MAP ▲", [SCEMU_BUTTON_SC88_MAP] = "EQ ▼",
	[SCEMU_BUTTON_KEY_SHIFT_LEFT] = "KEY SHIFT ◀", [SCEMU_BUTTON_KEY_SHIFT_RIGHT] = "KEY SHIFT ▶",
	[SCEMU_BUTTON_USER_INST] = "USER INST EDIT ON/OFF", [SCEMU_BUTTON_SELECT] = "USER INST EDIT SELECT",
	[SCEMU_BUTTON_EDIT1_LEFT] = "VIB RATE·ATTACK·DELAY ◀", [SCEMU_BUTTON_EDIT1_RIGHT] = "VIB RATE·ATTACK·DELAY ▶",
	[SCEMU_BUTTON_EDIT2_LEFT] = "VIB DEPTH·CUTOFF·DECAY·INSTRUMENT ◀", [SCEMU_BUTTON_EDIT2_RIGHT] = "VIB DEPTH·CUTOFF·DECAY·INSTRUMENT ▶",
	[SCEMU_BUTTON_EDIT3_LEFT] = "VIB DELAY·RESONANCE·RELEASE·VARIATION ◀", [SCEMU_BUTTON_EDIT3_RIGHT] = "VIB DELAY·RESONANCE·RELEASE·VARIATION ▶",
};

/* the SC-88VL keeps the EQ key and prints DELAY under KEY SHIFT; it has no lower face */
static const char *const label_sc88vl[SCEMU_BUTTON_COUNT] = {
	[SCEMU_BUTTON_SC55_MAP] = "SC-55 MAP ▲", [SCEMU_BUTTON_SC88_MAP] = "EQ ▼",
};

/* the SC-55mkII has neither map key nor lower face */
static const char *const label_sc55mk2[SCEMU_BUTTON_COUNT] = {
	[SCEMU_BUTTON_KEY_SHIFT_LEFT] = "KEY SHIFT ◀", [SCEMU_BUTTON_KEY_SHIFT_RIGHT] = "KEY SHIFT ▶",
};

static const char *const label_sc8850[SCEMU_BUTTON_COUNT] = {
	[SCEMU_BUTTON_MUTE] = "MUTE", [SCEMU_BUTTON_PREVIEW] = "PREVIEW (push the knob)",
	[SCEMU_BUTTON_PART_LEFT] = "PART ◀", [SCEMU_BUTTON_PART_RIGHT] = "PART ▶",
	[SCEMU_BUTTON_F1] = "F1", [SCEMU_BUTTON_F2] = "F2", [SCEMU_BUTTON_F3] = "F3", [SCEMU_BUTTON_F4] = "F4",
	[SCEMU_BUTTON_MAP] = "INST MAP", [SCEMU_BUTTON_VALUE] = "VALUE (push the dial)",
	[SCEMU_BUTTON_EDIT] = "EDIT", [SCEMU_BUTTON_DRUM] = "DRUM", [SCEMU_BUTTON_EFFECTS] = "EFFECTS",
	[SCEMU_BUTTON_SHIFT] = "SHIFT", [SCEMU_BUTTON_DOWN] = "VAR. ▼", [SCEMU_BUTTON_UP] = "INST ▲",
	[SCEMU_BUTTON_EXIT] = "EXIT", [SCEMU_BUTTON_ENTER] = "ENTER", [SCEMU_BUTTON_SOLO] = "SOLO",
	[SCEMU_BUTTON_DEC] = "DEC", [SCEMU_BUTTON_INC] = "INC",
};

const char *combo_button_label(panel_model_t panel, scemu_button_t button)
{
	if (button < 0 || button >= SCEMU_BUTTON_COUNT)
		return NULL;
	const char *const *own = panel == PANEL_MODEL_SC88 ? label_sc88
	                       : panel == PANEL_MODEL_SC88VL ? label_sc88vl
	                       : panel == PANEL_MODEL_SC55MK2 ? label_sc55mk2
	                       : panel == PANEL_MODEL_SC8850 ? label_sc8850 : NULL;
	if (own && own[button])
		return own[button];
	return panel == PANEL_MODEL_SC8850 ? NULL : label_common[button];
}

/* a key of a row's own panel; the table is checked against the panels in tests/test_menu.cpp,
   so the fallback is only there to keep a bad row from being undefined behaviour */
static const char *key_name(const combo_t *c, scemu_button_t b)
{
	const char *name = combo_button_label(c->panel, b);
	return name ? name : "?";
}

void combo_text(const combo_t *c, char *out, size_t size)
{
	bool together = c->timing == COMBO_TOGETHER && !c->power_on;
	int first = c->timing == COMBO_HOLD_THEN_PAIR && !c->power_on ? c->hold_count - 1 : c->hold_count;
	size_t n = (size_t)snprintf(out, size, together ? "press " : "hold ");
	for (int k = 0; k < first && n < size; k++)
		n += (size_t)snprintf(out + n, size - n, "%s%s", k ? " + " : "", key_name(c, c->hold[k]));
	if (c->power_on && n < size)
		n += (size_t)snprintf(out + n, size - n, " while switching on");
	if (c->press == SCEMU_BUTTON_COUNT)
		return;
	if (!together && n < size)
		n += (size_t)snprintf(out + n, size - n, ", then press ");
	for (int k = first; k < c->hold_count && n < size; k++)
		n += (size_t)snprintf(out + n, size - n, "%s + ", key_name(c, c->hold[k]));
	if (n < size)
		n += (size_t)snprintf(out + n, size - n, "%s%s", together ? " + " : "", key_name(c, c->press));
	if ((together || first < c->hold_count) && n < size)
		snprintf(out + n, size - n, " together");
}
